tap "anomalyco/tap"
tap "hashicorp/tap"

# ----------------------------------- development -----------------------------------
brew "bat"
cask "dbeaver-community"
brew "fzf"
brew "gh"
brew "n"
brew "eza"
brew "neovim"
brew "anomalyco/tap/opencode"
brew "tree-sitter-cli"
cask "orbstack"
cask "postman"
brew "hashicorp/tap/terraform"
brew "uv"
brew "yq"
cask "zed"
cask "kitty"
cask "claude"

# ----------------------------------- shell utilities -----------------------------------
brew "coreutils"
brew "mole"
brew "mas"
brew "herdr"

# ----------------------------------- productivity -----------------------------------
cask "notion"
cask "chatgpt"
cask "obsidian"

# ----------------------------------- common app -----------------------------------
cask "vlc"
cask "brave-browser"
cask "google-chrome"
cask "slack"
cask "spotify"
cask "discord"
cask "nordvpn"
cask "folx"
cask "telegram"
cask "vorssaint"

# ----------------------------------- mac app store -----------------------------------
mas "Xcode", id: 497799835
