#!/bin/zsh

echo "\nRunning homebrew/install\n"

# Check for Homebrew
if command -v brew >/dev/null; then
  echo "brew exists, skipping install"
else
  echo "brew doesn't exist, continuing with install"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# install packages (bundle)
brew bundle --file=$DOTFILES_ROOT/Brewfile