#!/bin/zsh

# Navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# Shortcuts
alias reload!=". ~/.zshrc"
alias cl="clear" # clear screen
alias dev="cd ~/dev"

# Listing
alias ls="exa -lahF --group-directories-first"
alias lsd="exa -lahFD"
alias lst="exa -T --group-directories-first" # tree view (specify depth -L=xxx)

# IP
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"

# Recursively delete `.DS_Store` files
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"

# bat
alias cat="bat"
