#!/bin/zsh

# shortcut to this dotfiles path is $DOTFILES_ROOT
export DOTFILES_ROOT=$HOME/.dotfiles


alias_file=($DOTFILES_ROOT/**/*/alias(N))
for alias in $alias_file; do
    source $alias
done

function_file=($DOTFILES_ROOT/**/*/function(N))
for function in $function_file; do
    source $function
done

# load theme
source $DOTFILES_ROOT/zsh/theme
